services:
  ioc:
    image: ghcr.io/cnpem/hvps-epics-ioc:latest
    build:
      context: ./
      dockerfile: docker/Dockerfile
      labels:
        org.opencontainers.image.source: https://github.com/cnpem/hvps-epics-ioc
      args:
        REPONAME: hvps-epics-ioc
        RUNDIR: /opt/hvps-epics-ioc/iocBoot/iocHVPSApp
        ENTRYPOINT: ./run.sh
        BUILD_STAGE_VERSION: latest
